apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-backend
  template:
    metadata:
      labels:
        app: os-backend
    spec:
      containers:
        - name: os-backend
          image: radkin/os_backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/testing_db?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: testing
            - name: SPRING_DATASOURCE_PASSWORD
              value: testingPassword
            - name: SPRING_JPA_HIBERATE_DDL_AUTO
              value: none
            - name: PROPUBLICA_TOKEN
              value: fakeToken1
            - name: OPENSECRETS_TOKEN
              value: fakeToken2
            - name: FEC_TOKEN
              value: fakeToken3