apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-claim0
  labels:
    app: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/noel/docker/postgres/docker-pg-vol/data"
  