CREATE TABLE IF NOT EXISTS senators
(
    id SERIAL PRIMARY KEY,
    pp_id TEXT,
    title TEXT,
    short_title TEXT,
    api_uri TEXT, 
    first_name TEXT,
    middle_name TEXT,
    last_name TEXT,
    suffix TEXT,
    date_of_birth DATE,
    gender TEXT,
    party TEXT,
    leadership_role TEXT,
    twitter_account TEXT,
    facebook_account TEXT,
    youtube_account TEXT,
    govtrack_id BIGINT,
    cspan_id BIGINT,
    votesmart_id BIGINT,
    icpsr_id BIGINT,
    crp_id TEXT,
    google_entity_id TEXT,
    fec_candidate_id TEXT,
    url TEXT,
    rss_url TEXT,
    contact_form TEXT,
    in_office BOOLEAN,
    dw_nominate DOUBLE PRECISION,
    seniority INTEGER,
    next_election TEXT,
    total_votes INTEGER,
    missed_votes INTEGER,
    total_present INTEGER,
    last_updated DATE,
    ocd_id TEXT,
    office TEXT,
    phone TEXT,
    state TEXT,
    senate_class INTEGER,
    state_rank TEXT,
    lis_id TEXT,
    missed_votes_pct DOUBLE PRECISION,
    votes_with_party_pct DOUBLE PRECISION,
    votes_against_party_pct DOUBLE PRECISION
);